broke up utils.py into multiple files
GabeGiro/EasyApplyJobsBot pull request #39
Opened 2024-08-19 14:27 UTC by alirahmnicode

2024-08-19 14:31 UTC, alirahmnicode commented
I created a utils package with several modules and moved functions into those modules.
If there is any problem let me know.

2024-08-26 08:43 UTC, GabeGiro requested changes
@alirahmnicode great work! 

Here are few more suggestions on how to improve.

2024-08-26 08:43 UTC, GabeGiro commented on utils/url_generator.py
> +from typing import List
To be more explicit, call this file linkedin_url_generator.py as it currently generates link only for Linkedin

2024-08-26 08:43 UTC, GabeGiro commented on utils/utils.py
> +#             f.write(text+ "\n")
I would put this in a file_writer.py or something similar

2024-08-26 08:43 UTC, GabeGiro commented on utils/utils.py
> +#             f.write(text+ "\n")
And after you separate this part, the rest are utils for the webdriver so you can rename it from utils.py -> driver.py

2024-08-26 08:43 UTC, GabeGiro commented on linkedin.py
> +        searchUrl = url_generator.LinkedinUrlGenerator.getGeneralSearchUrl()
```suggestion
        searchUrl = LinkedinUrlGenerator.getGeneralSearchUrl()
```

2024-08-26 08:43 UTC, GabeGiro commented on linkedin.py
> +        searchUrl = url_generator.LinkedinUrlGenerator.getGeneralSearchUrl()
Adjust the import so you can apply this suggestion

2024-08-26 08:43 UTC, GabeGiro commented on linkedin.py
> +from logger.logger import prGreen, prRed, prYellow
OPTIONAL: Remove direct usage of prGreen, prRed, prYellow outside of logger. 

This suggestion is optional and can be done in a separate PR

2025-02-05 20:28 UTC, GabeGiro commented
Hasn't been worked on for too long and I'm going to work on it now

2025-02-05 20:28 UTC, closed without merging